<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Docker.DotNet.Handler.Abstractions\Docker.DotNet.Handler.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="System" />
    <Using Include="System.Buffers" />
    <Using Include="System.Buffers.Text" />
    <Using Include="System.Collections.Generic" />
    <Using Include="System.Globalization" />
    <Using Include="System.IO" />
    <Using Include="System.Linq" />
    <Using Include="System.Net" />
    <Using Include="System.Net.Http" />
    <Using Include="System.Net.Http.Headers" />
    <Using Include="System.Net.Security" />
    <Using Include="System.Net.Sockets" />
    <Using Include="System.Reflection" />
    <Using Include="System.Runtime.CompilerServices" />
    <Using Include="System.Runtime.InteropServices" />
    <Using Include="System.Security" />
    <Using Include="System.Security.Authentication" />
    <Using Include="System.Security.Cryptography.X509Certificates" />
    <Using Include="System.Text" />
    <Using Include="System.Threading" />
    <Using Include="System.Threading.Tasks" />
    <Using Include="Docker.DotNet.Handler.Abstractions" />
    <Using Include="Microsoft.Extensions.Logging" />
  </ItemGroup>
</Project>
